### ISSUE TITLE
archiveするチャンネル一覧を出す

### ISSUE THREAD

**Issue by tyage** [kmc-jp/channel-killer#1]
n日以上発言のないチャンネル一覧をslackで出せるように

**Comment by tyage** [comment]
https://api.slack.com/methods/channels.info では, joinしていないチャンネルのlatestを取得できない.
全てのチャンネルにjoinしていないと、このAPIではn日以上発言がないチャンネルかどうかわからない.

services/exportsから取ってくるか？

**Comment by hatsusato** [comment]
ログはもう取れてるんだし、それを見るのではだめなのか。

**Comment by tyage** [comment]
slack-patronと連携する、ということはできるけど、あっちが止まるとこっちも死んでしまう

**Comment by nna774** [comment]
全部のチャンネルに入ればいいのでは〜(

**Comment by tyage** [comment]
そうするかー（joinするとlatestがjoinイベントになるので、1ヶ月くらい待つ必要がある

**Comment by nna774** [comment]
joinを無視したlatestとかであれすればいいのでは｡

**Comment by hatsusato** [comment]
全部のチャンネルに入ったら、一部の人に嫌われそう。名前的に。
channel-killer is watching you!

**Comment by nna774** [comment]
<○> <○>

**Comment by nna774** [comment]
一部の人が怒ってきたら何とかしたらいいのでは……｡

**Comment by tyage** [comment]
> joinを無視したlatestとかであれすればいいのでは｡
channels.infoではlatestは一件しか帰ってこないので、別の方法を使うしか無い

**Comment by nna774** [comment]
あーなるほど､内部に情報持ってるわけではなく､直接それが取れるAPIを叩いてるのかぁ｡

**Comment by tyage** [comment]
あっはいAPI叩いてます。
ログ取り機能をつけるのは微妙なので、slack-patronプラグインにするか、全チャンネルにjoinさせるか、といった感じかなぁと

**Comment by nna774** [comment]
パトロンのプラグインにするのはなんか微妙かなぁ って気もするし全joinでいいように思う｡

**Comment by pastak** [comment]
そもそも何のために更新の無いチャンネルのリストを取得したいんですか？

**Comment by pastak** [comment]
チャンネルをarchiveする必要性をあんまりよく分かってないのだけど・・・

**Comment by pastak** [comment]
activeなものが欲しいならarchiveしなくても、latestでソートした結果を出力するでは不十分なのですか？

**Comment by tyage** [comment]
エルラで、部員の数の2倍以上のチャンネルが増えると、新入生が混乱するので困るという話があって、とりあえず使われてないチャンネルはarchiveしてもいいよねという話になりました。

slackアプリからそのソート結果が見れるなら別にいいのだけど、新入生にそのページの閲覧を強いるのはハードルが高そう

**Comment by tyage** [comment]
チャンネル一覧を見た時にノイズ（使われてないチャンネル）が多いのはとにかく混乱を招きそうという判断です。
たぶん今後も増え続けるのでチャンネル数が500とか超えると、検索もしづらいし、現状でもチャンネル一覧を出すまでに結構負荷がかかっている気がする。

あとチャンネルをアーカイブしても、アーカイブ解除できるのでそんなに問題はないかと

**Comment by pastak** [comment]
あーarchiveって解除出来るんだ :bomb:

まぁ実際数は多いので仕方ないですねぇ。IRCの時ってどれくらいあったんだろう。

**Comment by tyage** [comment]
IRCの時もかなりの数のチャンネルがあったはずだけど、チャンネルリストに乗ってる数は少なかったはず。
slack側でチャンネルのグルーピングとか、そういう機能が付けば殺す必要は無いと思う。

**Comment by tyage** [comment]
botユーザーではチャンネルのjoinとarchiveができないということに気づいた！！！
ちゃんとユーザーアカウント作ることにします
